apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: grpcservice-internal-api
  description: Internal gRPC API endpoints exposed by grpcservice
spec:
  type: grpc
  lifecycle: experimental
  owner: your-team-name
  definition:
        $text:https://github.com/vamsi585/proto/blob/main/src/main/java/proto/greeting.proto
